feature/auth
mju-likelion/hephaistos pull request #2
Opened 2022-01-26 19:22 UTC by Crmal

2022-01-28 11:20 UTC, ypd06021 commented on src/api/auth.js
> +    err => {
@ndaemy 흐음 이 에러처리 문법을 다르게 할 수 도 있나요?

2022-01-28 11:20 UTC, ypd06021 commented on src/api/auth.js
> +            message: "이메일 형식이 올바르지 않습니다.",
err 나기 전에 req.body.email이 형식에 어긋나는지 코드가 필요한거 아닌가요 ?
bad request 가 이메일 형식 오류 말고 모종의 이유가 또 있지는 않을까요 ?

2022-01-28 11:20 UTC, ypd06021 commented on src/api/auth.js
> +    // 디비에 이메일이 존재하고 이메일 인증이 true
"이메일 인증이 true 면"  은 나중에 추가하실거죠 ?

2022-01-28 11:25 UTC, ypd06021 commented on src/api/auth.js
> +  transporter.sendMail(
@ndaemy 위에 transporter 를 변수에 담았으니깐, 함수를 호출할 필요 없이 얘도 변수에 담아버리면 어떨까요 ?
둘의 차이는 ?

2022-01-28 11:25 UTC, ypd06021 commented on src/api/auth.js
> +  const { email, password, name, phone, apply_univ, major, email_verify, status } = req.body;
status 빠져야한다는거 우선은 주석으로 표시해놓으면 좋을거같아요 나중에 까먹을수도 있으니깐 ..?

2022-02-02 13:15 UTC, ndaemy commented
일단 요거 풀리퀘 이름부터 기능으로 바꿔주세요 (ex. 인증 관련 라우터 작업)

2022-02-02 13:21 UTC, ndaemy requested changes

2022-02-02 13:21 UTC, ndaemy commented on src/api/auth.js
> +  transporter.sendMail(
함수를 호출하지 않고 변수에 담는다는게 무슨 소린지 이해를 못하겠어 🤔

2022-02-02 13:21 UTC, ndaemy commented on src/api/auth.js
> +    err => {
transporter.sendMail() 이라는 메서드가 두 번째 인자로 함수를 받는거라 불가능할듯?

2022-02-02 13:21 UTC, ndaemy commented on src/api/auth.js
> +      if (err) {
공식문서 보면 err 라는 파라미터 자체가 아래처럼 설명되고 있어서, if 문으로 체크 안해도 될듯
`err` is the error object if message failed

2022-02-02 13:21 UTC, ndaemy commented on src/api/auth.js
> +            message: "이메일 형식이 올바르지 않습니다.",
에러나기 전에 400 체크는 해야할듯
bad request 는 다른 형식 없을 거 같고

2022-02-02 13:21 UTC, ndaemy commented on src/api/auth.js
> +  const { email, password, name, phone, apply_univ, major, email_verify, status } = req.body;
ㅇㅇ 근데 req.body 에서 안 받는 값인건 맞으니까 이건 코드가 잘못됐어
재민아 api 문서 다시 봐봐

2022-02-02 13:42 UTC, ndaemy requested changes

2022-02-02 13:42 UTC, ndaemy commented on src/api/auth.js
> +const auth = express();
여기선 express() 가 아니고 Router() 여야지

2022-02-08 15:22 UTC, ndaemy requested changes

2022-02-08 15:22 UTC, ndaemy commented on .gitignore
> +dump
파일의 마지막에는 빈 라인 하나를 넣어주세요
왜 넣어야하는지는 [여기](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) 참고

2022-02-08 15:22 UTC, ndaemy commented on .gitignore
> +dump
그리고 dump.rdb 안걸리고 올라왔네요 이거 빼주세요

2022-02-08 15:22 UTC, ndaemy commented on src/api/auth.js
> +  const code = random(100000, 999999);
랜덤코드는 숫자로만 주지 말고 알파벳 + 숫자 6자리정도면 될 것 같아요
숫자만 있으면 보안적으로 너무 취약해서

2022-02-08 15:22 UTC, ndaemy commented on src/api/auth.js
> +  const code = random(100000, 999999);
그리고 랜덤하게 생성된 저 코드가 이미 레디스에 있는지도 확인해봐야 될거에요

2022-02-08 15:22 UTC, ndaemy commented on src/api/auth.js
> +  port: 6379,
요건 나중에 자기 자신이 아닌 컴퓨터로 바뀔 수도 있으니까 밑에처럼 환경변수로 바꾸는게 나을거같아요

2022-02-08 15:22 UTC, ndaemy commented on src/api/auth.js
> +      email_verify: true,
이거는 이러면 email 값을 추후에 알아낼 수가 없을거같은데, 구조가 좀 바뀌어야겠네요

2022-02-08 15:22 UTC, ndaemy commented on src/middleware/validator.js
> +exports.signVaildator = (req, res, next) => {
ES6 문법쓰기! :bbadda:

2022-02-08 15:22 UTC, ndaemy commented on src/middleware/validator.js
> +  const spe = password.search(/[`~!@@#$%^&*|₩₩₩'₩";:₩/?]/gi);
여기는 알파벳이 없으니까 /i 옵션이 필요없겠죠?

2022-02-08 15:22 UTC, ndaemy commented on src/middleware/validator.js
> +    spe < 0
이건 and가 아니라 or 여야 하지 않을까?

2022-02-08 15:22 UTC, ndaemy commented on src/middleware/validator.js
> +  const spe = password.search(/[`~!@@#$%^&*|₩₩₩'₩";:₩/?]/gi);
그리고 변수이름은 누가 봐도 알아볼 수 있게 씁시다
num은 워낙 많이 쓰이는 줄임말이니 괜찮지만
english나 specialCharacter 는 줄이면 못알아볼 수도 있을거같아요

그리고 단순히 숫자 영어 특수기호 가 아니라 검색결과니까 변수이름에 그런걸 알아볼수 있게도 들어가야 할 거 같아요

2022-02-09 13:28 UTC, ndaemy commented
그리고 풀리퀘 이름 바꿔주세요

2022-02-12 13:02 UTC, ndaemy requested changes

2022-02-12 13:02 UTC, ndaemy commented on package.json
> +    "connect-redis": "^6.1.1",
이거는 어디에 쓰는 라이브러리죠?

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +  // eslint-disable-next-line
요건 왜 disable 했죠?

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +  if (user) {
여긴 이중 조건문보다는 &&랑 [?.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) 연산자를 쓰는게 나아보여요

```
if (user && !user.emailVerify) {
  await User.destroy({ where: { email } });
else if (user?.email) {
  ...
}
```

이런식으로?

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +      await User.destroy({ where: { email } });
DB에서 굳이 row를 한번 destroy 하고 새로 만들기보다는 emailToken 필드만 업데이트 하면 문제가 되려나요?

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +    html: `<a href=http://localhost:3000/api/auth/email-verify/${token}>인증하기</a>`,
여기 href 속성 양쪽으로 "" 있어야죠?

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +    from: `pjm2207@likelion.org`,
이제 이거 우리 공식 계정으로 바꿉시다

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +    status: "writing",
의미없는 값 넣을바엔 null로 넣읍시다
DB 구조 바꿔서 올려놨어요
emailToken 필드도 추가했습니다

2022-02-12 13:02 UTC, ndaemy commented on src/middleware/validator.js
> +exports.signVaildator = (req, res, next) => {
이것도 해결해주세요

2022-02-12 13:02 UTC, ndaemy commented on src/middleware/validator.js
> +  // eslint-disable-next-line
이건 왜쓴거죠?

2022-02-12 13:02 UTC, ndaemy commented on src/middleware/validator.js
> +    // eslint-disable-next-line
이것도 왜쓴거죠?

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +      return res.status(403).json({
403은 Forbidden 이라, 여기서는 차라리 409 Conflict 가 나을거같아요

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +  // eslint-disable-next-line
이거 대체 왜 있는거냐고

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +  if (verifyToken) {
성공적인 코드가 가장 마지막으로 가도록 통일을 주는게 나아요
결국 실패하는 경우가 없으면 성공하는거니까

그렇지 않으면 라우터별로 읽는 순서가 다 다를거니까요

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +        email: verifyToken.email,
어차피 email로 찾았는데 email 필드를 변경할 필요가 있나요?

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +        major: "",
위에랑 동일하게 불필요한 값을 넣을바에는 null로 둡시다
이러면 불필요한 update를 해야하잖아요

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +/* eslint-disable */
이거 함부로 쓰지 말라구요 :bbadda:

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +// 회원가입(POST /api/auth/sign-up) =>
맨 뒤의 화살표는 뭐죠?

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +  // body에 값이 하나라도 존재하지 않는다면
주석은 있는데 해당 코드가 없네요? signValidator로 넘겼으면 주석도 삭제해주세요

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +  if (userEmail && userEmail.emailVerify) {
여기도 optional chaining 을 사용합시다

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +  });
여기도 성공하는 케이스를 가장 마지막으로 하는게 나을거같아요

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +      if (!userEmail.email_verify) {
이런 필드 없습니다
email_verify 아니고 emailVerify에요

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +    if (userEmail) {
여기도 이중 조건문을 안쓰는 방향이 나을거같아요

2022-02-12 13:02 UTC, ndaemy commented on src/api/auth.js
> +  } catch (error) {
여기서 error exception이 터지는 경우는 400이 아닌거같아요. 로직 다시 체크해주세요

2022-02-12 13:02 UTC, ndaemy commented on src/middleware/validator.js
> +    // eslint-disable-next-line
여기 왜 disable 했죠?

2022-02-12 13:02 UTC, ndaemy commented on src/middleware/validator.js
> +    specialCharactersCount < 0
이 부분 아예 하나의 util 함수로 빠지는게 코드 가독성에 더 도움이 될 것 같아요.

if (!isPasswordValid(password)) { ... }

이런식?

2022-02-12 13:02 UTC, ndaemy commented on src/middleware/validator.js
> +    return res.status(400).json({
같은 에러는 두 개의 조건문에서 처리하지 말고, 위에서 코드리뷰 한 것처럼 하나의 유틸 함수 안에서 처리하는게 코드 가독성이 좋은 방법입니다.

2022-02-12 13:02 UTC, ndaemy commented on .gitignore
> +# radis databases
radis 아니고 redis

2022-02-12 13:02 UTC, ndaemy commented on package.json
> +    "redis": "^4.0.2",
이제 redis 안쓰니 삭제해주시져

2022-02-12 17:50 UTC, Crmal commented on src/api/auth.js
> +      await User.destroy({ where: { email } });
update로 하게되면 create를 못하게 조건을 줘야하는데 update다음 return을 해버리면 메일전송에 문제가생겨요 전체로 if문으로 한번 더 감싸서 가능은 할텐데 그거보단 destroy가 보기더 깔끔할꺼같다고 생각합니다! destroy가 무거운작업이라면 바꾸겠습니다

2022-02-12 22:18 UTC, Crmal commented on src/api/auth.js
> +  if (userEmail && userEmail.emailVerify) {
여긴 안넣어도 되지않나요..??

2022-02-14 09:36 UTC, merged