apply 기능 관련 라우터
mju-likelion/hephaistos pull request #7
Opened 2022-02-15 22:05 UTC by Crmal

2022-02-16 00:11 UTC, ypd06021 commented on src/api/apply.js
> +    return res.status(500).json({
아직 테스트 덜 하긴했는데 알 수 없는 에러가 발생하였습니다는 뭔가요 ..?
401 로그인 먼저 해주세요 에러는 어디로 간거죠 ??

2022-02-16 17:54 UTC, ndaemy requested changes

2022-02-16 17:54 UTC, ndaemy commented on src/api/apply.js
> +    });
1. 특수 케이스가 아니면 에러 처리를 먼저 다 하고 마지막에 200 response를 주는게 낫다고!
2. 이건 결국에 "토큰이 없으면" 이라는거니까 차라리 앞쪽에 middleware로 걸러버리는게 나아. 미들웨어 어케 쓸지는 feature/users에 있는 checker 미들웨어 체크 고고

2022-02-16 17:54 UTC, ndaemy commented on src/api/apply.js
> +    });
사실 굳이 이렇게 catch 안해줘도 express 내부적으로 Error가 throw되면 500을 던지긴 해. 에러 메세지를 굳이 저거로 주고 싶은거 아니면 매번 catch 안해도 된다는 얘기

2022-02-16 17:54 UTC, ndaemy commented on src/api/apply.js
> +      }
이거 req.params.id가 userId랑 같아야되는게 아니라 user테이블의 id랑 같아야하는거일텐데?

2022-02-19 16:12 UTC, ndaemy approved these changes

2022-02-20 15:45 UTC, merged